#include <iostream>

int x = 10 ;

//namespace allows us to group named entities and giving them named scope

namespace ns1 {
    int  x = 1;
    //nesting namespace
    namespace ns2{
        int x = ns1::x; //will have value of global x
        int z = 43890;
    }
}

//spiting namespace definition
namespace ns1{
    int y =  70;

    //namespace can also have classes
    class cls1{
        public :
            cls1(){
                std::cout << "cls1 obj instantiated" << std::endl;
            }

            static void displayHello(){
                std::cout << "Hello" << std::endl;
            }
    };

}

//unnamed namespaces 
//these namespace have name generated by compiler and only available to progarm file
namespace {
    int y = 40; //will be treated as global variable
}

//another way of acessing namespcae
using namespace ns1::ns2;

int main(){
// namespace can be used in only global scope
    // namespace ns3{
    //     int x = 23;
    // }
    std::cout << ns1::ns2::x << std::endl;
    std::cout << ns1::y << std::endl;
    ns1::cls1 obj1;
    ns1::cls1::displayHello();
    std::cout << y << std::endl;
    std::cout << z << std::endl;
    return 0;
}